apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: w9-platform-root
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/CHANGE_ME/CHANGE_ME.git
    targetRevision: main
    path: cloud/w9/lab/argocd
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true

